export default function VersionHistoryPanel({
  versions,
  onRestore,
  onDelete,
  onClear,
}) {
  return (
    <div className="rounded-xl border bg-white shadow-sm">
      <div className="flex flex-col gap-3 border-b p-5 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="text-lg font-semibold text-slate-900">
            Version History
          </h2>
          <p className="mt-1 text-sm text-slate-500">
            Track prompt versions generated by Improve, Evaluate, and Convert actions.
          </p>
        </div>

        <button
          onClick={onClear}
          className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm text-slate-700 hover:bg-slate-50"
        >
          Clear History
        </button>
      </div>

      {versions.length === 0 ? (
        <div className="p-6 text-sm text-slate-500">
          No version history available yet.
        </div>
      ) : (
        <div className="divide-y divide-slate-200 p-4">
          {versions.map((version) => (
            <div
              key={version.id}
              className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4"
            >
              <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
                <div className="min-w-0">
                  <div className="text-sm font-semibold text-slate-900">
                    {version.action}
                  </div>
                  <div className="mt-1 text-xs text-slate-500">
                    {new Date(version.timestamp).toLocaleString()}
                  </div>
                  {version.generatedPrompt ? (
                    <div className="mt-2 text-sm text-slate-600">
                      {version.generatedPrompt.length > 120
                        ? `${version.generatedPrompt.slice(0, 120)}...`
                        : version.generatedPrompt}
                    </div>
                  ) : null}
                </div>

                <div className="flex flex-wrap gap-2">
                  <button
                    onClick={() => onRestore(version.id)}
                    className="rounded-lg bg-blue-600 px-3 py-2 text-sm text-white hover:bg-blue-700"
                  >
                    Restore
                  </button>
                  <button
                    onClick={() => onDelete(version.id)}
                    className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-700 hover:bg-slate-50"
                  >
                    Delete
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}